### PR TITLE
Streamlined Names

### PR DESCRIPTION
**Pull request by elricco**
Changed rex_babelfish to babelfish in utils and every call for easier replacement.

This time with better indention ;)

### CODE REVIEW

**Comment by starlord** [comment]
I am not sure why replacement is easier then but I think we should keep it like this due to compat reasons etc.

Great indention though ;)

**Comment by elricco** [comment]
If you replace every "babelfish" with "rex_myaddon" you get "rex_rex_myaddon_utils.inc.php" for example in config.inc.php and rex_rex_myaddon_utlis as class call. It was my intention to get this easier, because everything else is also "just" babelfish.

Thank you :D

**Comment by starlord** [comment]
Now I understand :) there is a simple solution to that: be more creative and stop prefixing your addons with "rex" ;)

**Comment by elricco** [comment]
I already do so, so to get rid of everything "rex" I did this commit ;)

**Comment by starlord** [comment]
but the prefix in the class name is not that bad as you still belong to the rex universe where all classes / functions are rex prefiexed (due to missing namespace convetions).

**Pull request closed without merging**
